# Generated by Django 4.2.7 on 2023-11-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_fiscale', models.CharField(max_length=16)),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Esame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(null=True)),
                ('valore', models.FloatField()),
                ('unita_misura', models.CharField(max_length=20)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionale.paziente')),
            ],
        ),
    ]
